language: php

install:
  - travis_wait composer install --profile --no-interaction
  - mkdir -p build/logs

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 8.0
  - 8.1
  - 8.2

script:
  - ./vendor/bin/phpunit

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - travis_retry php vendor/bin/codacycoverage clover ./build/logs/clover.xml
